sudo: required

services:
  - docker

before_install:
  - docker build -t alexis/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true alexis/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: eu-west-1
  app: docker-react
  env: DockerReact-env
  bucket-name: elasticbeanstalk-eu-west-1-780164487719
  bucket-path: docker-react
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
